# -*- coding: utf-8 -*-
"""AIML LABSHEET 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ijsxu9hpoa7VtUEXWjactpeU_CxC2LoC
"""

#1d array
import numpy as np
A1=np.array([1,2,3,4])
print(A1)

type(A1)

A1.shape

#2d array
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

type(A2)

A2.shape

#3d array
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)
type(A3)
A3.shape

import numpy as np
z1=np.zeros(3)
z1

z1=np.zeros(3,dtype=int)
z1

z1.shape

z1.size

z1.ndim

type(z1)

z2=np.zeros((3,4))
z2

z2=np.zeros((3,4),dtype=int)
z2

type(z2)

z2.ndim

z3=np.zeros((2,3,4))
z3

z3.shape
z3.ndim

type(z3)

z3=np.zeros((3,4),dtype=int)
z3

z3.shape

z3.size

z3.ndim

import numpy as np
a1=np.ones(3)
a1

a1=np.ones(3,dtype=int)
a1

a1.size

a1.ndim

a2=np.ones([3,4],dtype=int)
a2

type(a2)

a2.shape

a3=np.ones([4,2,3])
a3

type(a3)

f1=np.full(3,9)
f1

f1=np.full(3,9,dtype=float)
f1



f2=np.full((9,2,3),9)
f2

"""MATPLOT"""

!pip install matplotlib

import matplotlib.pyplot as plt

#linechat
yield_Apples=[0.895,0.91,0.919,0.926,0.929,0.931]
plt.plot(yield_Apples)
plt

years=[2010,2011,2012,2013,2014,2015]
yield_Apples=[0.895,0.91,0.919,0.926,0.929,0.931]
plt.plot(years,yield_Apples)

#axis label
plt.title("yield Apples")
plt.plot(years,yield_Apples)
plt.xlabel("year")
plt.ylabel("yield(tons per hectare)");

years=range(2000,2007) #change this to range(2000,2007) so that the length is 7
apples=[0.895,0.91,0.926,0.929,0.934,0.936,0.937]
oranges=[0.962,0.941,0.930,0.918,0.908,0.907,0.904] #removed the last element of oranges so that it matches the length of 'years'
plt.plot(years,apples)
plt.plot(years,oranges)
plt.xlabel('years')
plt.ylabel('yield')

#title and Legend
year=range(2000,2008)

apple=[0.895,0.91,0.919,0.926,0.929,0.934,0.936,0.937]
oranges=[0.962,0.941,0.930,0.918,0.908,0.907,0.904,0.901]
plt.plot(year,apple)
plt.plot(year,oranges)
plt.xlabel('Year')
plt.ylabel('Yield')
plt.title('Crop yields in Kanto')
plt.legend(['Apples','Oranges'])

plt.plot(year,apple,marker='o')
plt.plot(year,oranges,marker='x')

plt.ylabel('Yield')
plt.title('Crop yields in Kanto')
plt.legend(['Apples','Oranges'])

plt.plot(year,apple,marker='s',c='b',ls='-',lw=2,ms=8,mew=2,mec='red')
plt.plot(year,oranges,marker='o',c='r',ls='--',lw=3,ms=10,alpha=0.5)
plt.ylabel('Yield')
plt.title('Crop yields in Kanto')
plt.legend(['Apples','Oranges'])

plt.plot(year,oranges,'or')
plt.title('yield of oranges')

plt.figure(figsize=(4,4))

plt.plot(year,oranges,'or')
plt.title('yield of oranges')

import matplotlib.pyplot as plt
#data to display on plots
x=[3,1,3,12,1,4,4]
y=[3,2,1,4,5,6,7]
plt.bar(x,y)
plt.title("Bar chart")
plt.legend(["bar"])
plt.show()

import matplotlib.pyplot as plt
#data to display on plots
x=[3,1,3,12,1,4,4]
y=[3,2,1,4,5,6,7]
plt.scatter(x,y)
plt.legend("A")
plt.xlabel('x')
plt.ylabel('y')
plt.title("scatter chart")
plt.show()

"""PIE CHART"""

import matplotlib.pyplot as plt
x=[1,2,3,4]
e=(0.1,0,0,0)
plt.pie(x,explode=e)
plt.title("pie chart")
plt.show()

import matplotlib.pyplot as plt
x=[1,2,3,4]
e=(0.1,0,0.5,0)
plt.pie(x,explode=e)
plt.title("pie chart")
plt.show()

"""#PANDAS"""

import pandas as pd
df=pd.read_csv('/content/empdata.csv')
df

df.head(2)

df.tail()

df.info()

df.describe()

df.shape

type(df)

df.columns

df.Empid

df[['Empid','Salary']]

df1=df.copy()
df

df1=df1.drop_duplicates()
df1

df.columns=[i.upper() for i in df.columns]
df.columns

df.isna().sum()

df.dropna(axis=1)